apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: placeholder
          ports:
            - containerPort: 7007
          env:
            - name: NODE_ENV
              value: production
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: AUTH_GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-secrets
                  key: AUTH_GOOGLE_CLIENT_ID            
            - name: AUTH_GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-secrets
                  key: AUTH_GOOGLE_CLIENT_SECRET            
            - name: GCS_CLIENT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: google-secrets
                  key: GCS_CLIENT_EMAIL            
            - name: GCS_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: google-secrets
                  key: GCS_PRIVATE_KEY
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: google-secrets
                  key: GITHUB_TOKEN
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 7007
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 7007
            initialDelaySeconds: 30
            periodSeconds: 15